#!/bin/bash

MY_PATH="$(realpath "$0")"
MY_DIR="$(dirname "$MY_PATH")"

rm -rvf "$(realpath ~)"/.cache/winetricks

(
cd dxvk || exit 1
mkdir -pv "$(realpath ~)"/.cache/winetricks/dxvkmanual
./package-release.sh release "$(realpath ~/.cache/winetricks/dxvkmanual)" || exit 1
)

(
cd vkd3d-proton || exit 1
mkdir -pv "$(realpath ~)"/.cache/winetricks/vkd3dmanual
./package-release.sh release "$(realpath ~/.cache/winetricks/vkd3dmanual)" || exit 1
)

"$MY_DIR"/winetricks dxvkmanual vkd3dmanual || exit 1

