#!/bin/bash

cores=$(nproc)

# Check if the script is being run as root
if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root (use sudo)."
    exit 1
fi

#initial setup

tar -xvf Python-3.13.7.tar.xz || exit 1
tar -xvf flit_core-3.12.0.tar.gz || exit 1
tar -xvf packaging-25.0.tar.gz || exit 1
tar -xvf wheel-0.46.1.tar.gz || exit 1
tar -xvf setuptools-80.9.0.tar.gz || exit 1
tar -xvf ninja-1.13.1.tar.gz || exit 1
tar -xvf meson-1.9.1.tar.gz || exit 1

#Python-3.13.7

(
    cd Python-3.13.7 || exit 1
    ./configure --enable-optimizations
    make -j"$cores"
    make -j"$cores" install
)

#flit_core-3.12.0
(
    cd flit_core-3.12.0 || exit 1
    pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps "$PWD"
    pip3 install --no-index --find-links dist flit_core
)

#packaging-25.0
(
    cd packaging-25.0 || exit 1
    pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps "$PWD"
    pip3 install --no-index --find-links dist packaging
)

#wheel-0.46.1
(
    cd wheel-0.46.1 || exit 1
    pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps "$PWD"
    pip3 install --no-index --find-links dist wheel
)

#setuptools-80.9.0
(
    cd setuptools-80.9.0 || exit 1
    pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps "$PWD"
    pip3 install --no-index --find-links dist setuptools
)

#ninja-1.13.1
(
    cd ninja-1.13.1 || exit 1
    python3 configure.py --bootstrap --verbose
    install -vm755 ninja /usr/local/bin/
    install -vDm644 misc/bash-completion /usr/local/share/bash-completion/completions/ninja
    install -vDm644 misc/zsh-completion  /usr/local/share/zsh/site-functions/_ninja
)

#meson-1.9.1
(
    cd meson-1.9.1 || exit 1
    pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps "$PWD"
    pip3 install --no-index --find-links dist meson
    install -vDm644 data/shell-completions/bash/meson /usr/local/share/bash-completion/completions/meson
    install -vDm644 data/shell-completions/zsh/_meson /usr/local/share/zsh/site-functions/_meson

)
