#!/bin/bash

installdir="/usr/local"

realdir="$(realpath "$installdir")"

workingdir="$PWD"

cores=$(nproc)

addgccdeps() {
tar -xvf "$workingdir"/mpfr-4.2.2.tar.xz
mv -v mpfr-4.2.2 mpfr
tar -xvf "$workingdir"/gmp-6.3.0.tar.xz
mv -v gmp-6.3.0 gmp
tar -xvf "$workingdir"/mpc-1.3.1.tar.gz
mv -v mpc-1.3.1 mpc
}

# Check if the script is being run as root
if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root (use sudo)."
    exit 1
fi

#initial setup
tar -xvf binutils-2.45.tar.xz || exit 1
tar -xvf gcc-15.2.0.tar.xz || exit 1
tar -xvf mingw-w64-v13.0.0.tar.bz2 || exit 1

#MinGW - w64 - headers - 13.0.0

(
cd mingw-w64-v13.0.0 || exit 1
addgccdeps
mkdir build-x86_64-headers
(
cd    build-x86_64-headers || exit 1
addgccdeps
../mingw-w64-headers/configure --prefix="$realdir"/x86_64-w64-mingw32 \
                               --host=x86_64-w64-mingw32        \
                               --enable-sdk=all                 \
                               --with-default-msvcrt=msvcrt
make -j"$cores" install
)



mkdir build-i686-headers
(
cd    build-i686-headers || exit 1
addgccdeps
../mingw-w64-headers/configure --prefix="$realdir"/i686-w64-mingw32 \
                               --host=i686-w64-mingw32        \
                               --enable-sdk=all               \
                               --with-default-msvcrt=msvcrt
make -j"$cores" install
)
)

#MinGW - w64 - Binutils - 2.45

(
cd binutils-2.45 || exit 1
addgccdeps
mkdir build-x86_64
(
cd    build-x86_64 || exit 1
addgccdeps
../configure --prefix="$realdir"                                \
             --target=x86_64-w64-mingw32                  \
             --infodir="$realdir"/share/info/x86_64-w64-mingw32 \
             --disable-nls                                \
             --disable-werror

make -j"$cores"

make -j"$cores"   DESTDIR="$PWD"/DESTDIR install
rm -v  DESTDIR"$realdir"/lib/bfd-plugins/libdep.so
cp -Rv DESTDIR"$realdir"/* "$realdir"
rm -rf DESTDIR
)


mkdir build-i686
(
cd    build-i686 || exit 1
addgccdeps
../configure --prefix="$realdir"                             \
             --target=i686-w64-mingw32                  \
             --infodir="$realdir"/share/info/i686-w64-mingw32 \
             --disable-nls                              \
             --disable-werror

make -j"$cores"

make -j"$cores"   DESTDIR="$PWD"/DESTDIR install
rm -v  DESTDIR"$realdir"/lib/bfd-plugins/libdep.so
cp -Rv DESTDIR"$realdir"/* "$realdir"
rm -rf DESTDIR
)
)

#Static MinGW-w64-GCC-15.2.0


(
cd gcc-15.2.0 || exit 1

addgccdeps

mkdir build-x86_64-mingw-w64-static
(
cd    build-x86_64-mingw-w64-static || exit 1
addgccdeps
../configure --prefix="$realdir"         \
             --target=x86_64-w64-mingw32 \
             --disable-shared            \
             --disable-multilib          \
             --disable-threads           \
             --enable-languages=c,c++

make -j"$cores" all-gcc
make -j"$cores" install-gcc
)

mkdir build-i686-mingw-w64-static
(
cd    build-i686-mingw-w64-static || exit 1
addgccdeps
../configure --prefix="$realdir"         \
             --target=i686-w64-mingw32 \
             --disable-shared            \
             --disable-multilib          \
             --disable-threads           \
             --enable-languages=c,c++

make -j"$cores" all-gcc
make -j"$cores" install-gcc
)
)

#MinGW-w64-13.0.0

(
cd mingw-w64-v13.0.0 || exit 1
addgccdeps
mkdir build-x86_64
(
cd build-x86_64 || exit 1
addgccdeps
../configure --prefix="$realdir"/x86_64-w64-mingw32 \
             --host=x86_64-w64-mingw32        \
             --disable-lib32                  \
             --enable-experimental            \
             --with-default-msvcrt=msvcrt

make -j"$cores"
make -j"$cores" install
)

mkdir build-x86_64-winpthreads
(
cd    build-x86_64-winpthreads || exit 1
addgccdeps
../mingw-w64-libraries/winpthreads/configure \
            --prefix="$realdir"/x86_64-w64-mingw32 \
            --host=x86_64-w64-mingw32        \
            --disable-lib32                  \
            --with-default-msvcrt=msvcrt

make -j"$cores"
make -j"$cores" install
)


mkdir build-i686
(
cd build-i686 || exit 1
addgccdeps
../configure --prefix="$realdir"/i686-w64-mingw32 \
             --host=i686-w64-mingw32        \
             --disable-lib64                  \
             --enable-experimental            \
             --with-default-msvcrt=msvcrt

make -j"$cores"
make -j"$cores" install
)

mkdir build-i686-winpthreads
(
cd    build-i686-winpthreads || exit 1
addgccdeps
../mingw-w64-libraries/winpthreads/configure \
            --prefix="$realdir"/i686-w64-mingw32 \
            --host=i686-w64-mingw32        \
            --disable-lib64                  \
            --with-default-msvcrt=msvcrt

make -j"$cores"
make -j"$cores" install
)
)

#MinGW-w64-GCC-15.2.0

(
cd gcc-15.2.0 || exit 1
addgccdeps
mkdir build-x86_64-mingw-w64
(
cd    build-x86_64-mingw-w64 || exit 1
addgccdeps
../configure --prefix="$realdir"               \
             --target=x86_64-w64-mingw32 \
             --enable-threads=posix      \
             --enable-shared             \
             --disable-multilib          \
             --enable-languages=c,c++

make -j"$cores"
make -j"$cores" install
)

ln -sfv x86_64-w64-mingw32-gcc "$realdir"/bin/x86_64-w64-mingw32-cc
strip "$realdir"/libexec/gcc/x86_64-w64-mingw32/15.2.0/{cc1*,collect2,lto*}


mkdir build-i686-mingw-w64
(
cd    build-i686-mingw-w64 || exit 1
addgccdeps
../configure --prefix="$realdir"               \
             --target=i686-w64-mingw32 \
             --enable-threads=posix      \
             --enable-shared             \
             --disable-multilib          \
             --enable-languages=c,c++

make -j"$cores"
make -j"$cores" install
)

ln -sfv i686-w64-mingw32-gcc "$realdir"/bin/i686-w64-mingw32-cc
strip "$realdir"/libexec/gcc/i686-w64-mingw32/15.2.0/{cc1*,collect2,lto*}
)


#tests

echo "int main(){}" >> main.c
cp -v main.c main.cpp
gcc main.c
./a.out

rm -v a.out
g++ main.cpp
./a.out

rm -v a.out main.{c,cpp}



cat >> main.c << "EOF"
#include <stdio.h>
int main(){}
EOF

cp main.{c,cpp}
sed -i 's/stdio.h/iostream/g' main.cpp

x86_64-w64-mingw32-gcc main.c
rm -v a.exe
x86_64-w64-mingw32-g++ main.cpp
rm -v a.exe main.{c,cpp}




cat >> main.c << "EOF"
#include <stdio.h>
int main(){}
EOF

cp main.{c,cpp}
sed -i 's/stdio.h/iostream/g' main.cpp

i686-w64-mingw32-gcc main.c
rm -v a.exe
i686-w64-mingw32-g++ main.cpp
rm -v a.exe main.{c,cpp}
